# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sgd_svm_pb2 as sgd__svm__pb2


class SGD_SVMStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetData = channel.unary_unary(
        '/SGD_SVM/GetData',
        request_serializer=sgd__svm__pb2.GradientUpdate.SerializeToString,
        response_deserializer=sgd__svm__pb2.DataSample.FromString,
        )


class SGD_SVMServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetData(self, request, context):
    """rpc GetData() returns (DataSample) {};
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SGD_SVMServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetData': grpc.unary_unary_rpc_method_handler(
          servicer.GetData,
          request_deserializer=sgd__svm__pb2.GradientUpdate.FromString,
          response_serializer=sgd__svm__pb2.DataSample.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SGD_SVM', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
