# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sgd_svm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sgd_svm.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rsgd_svm.proto\"@\n\nDataSample\x12\x13\n\x0b\x64\x61ta_sample\x18\x01 \x01(\t\x12\r\n\x05param\x18\x02 \x01(\t\x12\x0e\n\x06target\x18\x03 \x01(\t\"%\n\x0eGradientUpdate\x12\x13\n\x0bgrad_update\x18\x01 \x01(\t24\n\x07SGD_SVM\x12)\n\x07GetData\x12\x0f.GradientUpdate\x1a\x0b.DataSample\"\x00\x62\x06proto3')
)




_DATASAMPLE = _descriptor.Descriptor(
  name='DataSample',
  full_name='DataSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_sample', full_name='DataSample.data_sample', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param', full_name='DataSample.param', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='DataSample.target', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=81,
)


_GRADIENTUPDATE = _descriptor.Descriptor(
  name='GradientUpdate',
  full_name='GradientUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='grad_update', full_name='GradientUpdate.grad_update', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['DataSample'] = _DATASAMPLE
DESCRIPTOR.message_types_by_name['GradientUpdate'] = _GRADIENTUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataSample = _reflection.GeneratedProtocolMessageType('DataSample', (_message.Message,), dict(
  DESCRIPTOR = _DATASAMPLE,
  __module__ = 'sgd_svm_pb2'
  # @@protoc_insertion_point(class_scope:DataSample)
  ))
_sym_db.RegisterMessage(DataSample)

GradientUpdate = _reflection.GeneratedProtocolMessageType('GradientUpdate', (_message.Message,), dict(
  DESCRIPTOR = _GRADIENTUPDATE,
  __module__ = 'sgd_svm_pb2'
  # @@protoc_insertion_point(class_scope:GradientUpdate)
  ))
_sym_db.RegisterMessage(GradientUpdate)



_SGD_SVM = _descriptor.ServiceDescriptor(
  name='SGD_SVM',
  full_name='SGD_SVM',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=122,
  serialized_end=174,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetData',
    full_name='SGD_SVM.GetData',
    index=0,
    containing_service=None,
    input_type=_GRADIENTUPDATE,
    output_type=_DATASAMPLE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SGD_SVM)

DESCRIPTOR.services_by_name['SGD_SVM'] = _SGD_SVM

# @@protoc_insertion_point(module_scope)
