# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SVM.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SVM.proto',
  package='project',
  syntax='proto3',
  serialized_pb=_b('\n\tSVM.proto\x12\x07project\"5\n\x03Row\x12\r\n\x05label\x18\x01 \x01(\t\x12\x1f\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x0e.project.Entry\"I\n\x0cWeightUpdate\x12\x19\n\x03row\x18\x01 \x01(\x0b\x32\x0c.project.Row\x12\x0f\n\x07indexes\x18\x02 \x03(\x03\x12\r\n\x05label\x18\x03 \x01(\t\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\t\"%\n\x05\x45ntry\x12\r\n\x05index\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x01\x32:\n\x03SVM\x12\x33\n\nGetWeights\x12\x15.project.WeightUpdate\x1a\x0c.project.Row\"\x00\x62\x06proto3')
)




_ROW = _descriptor.Descriptor(
  name='Row',
  full_name='project.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='project.Row.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entries', full_name='project.Row.entries', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=75,
)


_WEIGHTUPDATE = _descriptor.Descriptor(
  name='WeightUpdate',
  full_name='project.WeightUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='project.WeightUpdate.row', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='indexes', full_name='project.WeightUpdate.indexes', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='project.WeightUpdate.label', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=150,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='project.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='project.Status.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=176,
)


_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='project.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='project.Entry.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='project.Entry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=215,
)

_ROW.fields_by_name['entries'].message_type = _ENTRY
_WEIGHTUPDATE.fields_by_name['row'].message_type = _ROW
DESCRIPTOR.message_types_by_name['Row'] = _ROW
DESCRIPTOR.message_types_by_name['WeightUpdate'] = _WEIGHTUPDATE
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Entry'] = _ENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Row = _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), dict(
  DESCRIPTOR = _ROW,
  __module__ = 'SVM_pb2'
  # @@protoc_insertion_point(class_scope:project.Row)
  ))
_sym_db.RegisterMessage(Row)

WeightUpdate = _reflection.GeneratedProtocolMessageType('WeightUpdate', (_message.Message,), dict(
  DESCRIPTOR = _WEIGHTUPDATE,
  __module__ = 'SVM_pb2'
  # @@protoc_insertion_point(class_scope:project.WeightUpdate)
  ))
_sym_db.RegisterMessage(WeightUpdate)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'SVM_pb2'
  # @@protoc_insertion_point(class_scope:project.Status)
  ))
_sym_db.RegisterMessage(Status)

Entry = _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), dict(
  DESCRIPTOR = _ENTRY,
  __module__ = 'SVM_pb2'
  # @@protoc_insertion_point(class_scope:project.Entry)
  ))
_sym_db.RegisterMessage(Entry)



_SVM = _descriptor.ServiceDescriptor(
  name='SVM',
  full_name='project.SVM',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=217,
  serialized_end=275,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetWeights',
    full_name='project.SVM.GetWeights',
    index=0,
    containing_service=None,
    input_type=_WEIGHTUPDATE,
    output_type=_ROW,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SVM)

DESCRIPTOR.services_by_name['SVM'] = _SVM

# @@protoc_insertion_point(module_scope)
