# Use an official Python runtime as a parent image
FROM python:3.6

# Creating Application Source Code Directory



# Set the working directory to /app
WORKDIR /app


ADD test.py /app

ENTRYPOINT ["python","-u", "/app/test.py"]