# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SVM.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SVM.proto',
  package='project',
  syntax='proto3',
  serialized_pb=_b('\n\tSVM.proto\x12\x07project\"\x06\n\x04Null\"V\n\x0bNode_Config\x12\x1b\n\x13\x63oordinator_address\x18\x01 \x01(\t\x12\x17\n\x0fworkers_address\x18\x02 \x03(\t\x12\x11\n\tworker_nb\x18\x03 \x01(\x05\"P\n\x0fLearning_Config\x12\n\n\x02lr\x18\x01 \x01(\x02\x12\x10\n\x08tot_iter\x18\x02 \x01(\x02\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\x12\x0b\n\x03reg\x18\x04 \x01(\x02\"b\n\x03Row\x12\r\n\x05label\x18\x01 \x01(\t\x12\x1f\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x0e.project.Entry\x12\x18\n\x10iteration_number\x18\x03 \x01(\x05\x12\x11\n\tworker_nb\x18\x04 \x01(\x05\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\t\"%\n\x05\x45ntry\x12\r\n\x05index\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x01\x32\xb5\x02\n\x03SVM\x12+\n\nGetWeights\x12\x0c.project.Row\x1a\r.project.Null\"\x00\x12\x35\n\x0cSendNodeInfo\x12\x14.project.Node_Config\x1a\r.project.Null\"\x00\x12=\n\x10SendLearningInfo\x12\x18.project.Learning_Config\x1a\r.project.Null\"\x00\x12\x36\n\x14SendCompletionSignal\x12\r.project.Null\x1a\r.project.Null\"\x00\x12\'\n\x05Start\x12\r.project.Null\x1a\r.project.Null\"\x00\x12*\n\tGetUpdate\x12\x0c.project.Row\x1a\r.project.Null\"\x00\x62\x06proto3')
)




_NULL = _descriptor.Descriptor(
  name='Null',
  full_name='project.Null',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=28,
)


_NODE_CONFIG = _descriptor.Descriptor(
  name='Node_Config',
  full_name='project.Node_Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coordinator_address', full_name='project.Node_Config.coordinator_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workers_address', full_name='project.Node_Config.workers_address', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worker_nb', full_name='project.Node_Config.worker_nb', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=116,
)


_LEARNING_CONFIG = _descriptor.Descriptor(
  name='Learning_Config',
  full_name='project.Learning_Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lr', full_name='project.Learning_Config.lr', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tot_iter', full_name='project.Learning_Config.tot_iter', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='project.Learning_Config.batch_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reg', full_name='project.Learning_Config.reg', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=198,
)


_ROW = _descriptor.Descriptor(
  name='Row',
  full_name='project.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='project.Row.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entries', full_name='project.Row.entries', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iteration_number', full_name='project.Row.iteration_number', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worker_nb', full_name='project.Row.worker_nb', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=298,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='project.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='project.Status.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=324,
)


_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='project.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='project.Entry.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='project.Entry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=363,
)

_ROW.fields_by_name['entries'].message_type = _ENTRY
DESCRIPTOR.message_types_by_name['Null'] = _NULL
DESCRIPTOR.message_types_by_name['Node_Config'] = _NODE_CONFIG
DESCRIPTOR.message_types_by_name['Learning_Config'] = _LEARNING_CONFIG
DESCRIPTOR.message_types_by_name['Row'] = _ROW
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Entry'] = _ENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Null = _reflection.GeneratedProtocolMessageType('Null', (_message.Message,), dict(
  DESCRIPTOR = _NULL,
  __module__ = 'SVM_pb2'
  # @@protoc_insertion_point(class_scope:project.Null)
  ))
_sym_db.RegisterMessage(Null)

Node_Config = _reflection.GeneratedProtocolMessageType('Node_Config', (_message.Message,), dict(
  DESCRIPTOR = _NODE_CONFIG,
  __module__ = 'SVM_pb2'
  # @@protoc_insertion_point(class_scope:project.Node_Config)
  ))
_sym_db.RegisterMessage(Node_Config)

Learning_Config = _reflection.GeneratedProtocolMessageType('Learning_Config', (_message.Message,), dict(
  DESCRIPTOR = _LEARNING_CONFIG,
  __module__ = 'SVM_pb2'
  # @@protoc_insertion_point(class_scope:project.Learning_Config)
  ))
_sym_db.RegisterMessage(Learning_Config)

Row = _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), dict(
  DESCRIPTOR = _ROW,
  __module__ = 'SVM_pb2'
  # @@protoc_insertion_point(class_scope:project.Row)
  ))
_sym_db.RegisterMessage(Row)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'SVM_pb2'
  # @@protoc_insertion_point(class_scope:project.Status)
  ))
_sym_db.RegisterMessage(Status)

Entry = _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), dict(
  DESCRIPTOR = _ENTRY,
  __module__ = 'SVM_pb2'
  # @@protoc_insertion_point(class_scope:project.Entry)
  ))
_sym_db.RegisterMessage(Entry)



_SVM = _descriptor.ServiceDescriptor(
  name='SVM',
  full_name='project.SVM',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=366,
  serialized_end=675,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetWeights',
    full_name='project.SVM.GetWeights',
    index=0,
    containing_service=None,
    input_type=_ROW,
    output_type=_NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendNodeInfo',
    full_name='project.SVM.SendNodeInfo',
    index=1,
    containing_service=None,
    input_type=_NODE_CONFIG,
    output_type=_NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendLearningInfo',
    full_name='project.SVM.SendLearningInfo',
    index=2,
    containing_service=None,
    input_type=_LEARNING_CONFIG,
    output_type=_NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendCompletionSignal',
    full_name='project.SVM.SendCompletionSignal',
    index=3,
    containing_service=None,
    input_type=_NULL,
    output_type=_NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Start',
    full_name='project.SVM.Start',
    index=4,
    containing_service=None,
    input_type=_NULL,
    output_type=_NULL,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUpdate',
    full_name='project.SVM.GetUpdate',
    index=5,
    containing_service=None,
    input_type=_ROW,
    output_type=_NULL,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SVM)

DESCRIPTOR.services_by_name['SVM'] = _SVM

# @@protoc_insertion_point(module_scope)
