# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import SVM_pb2 as SVM__pb2


class SVMStub(object):
  """Interface exported by the server.

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetWeights = channel.unary_unary(
        '/project.SVM/GetWeights',
        request_serializer=SVM__pb2.Row.SerializeToString,
        response_deserializer=SVM__pb2.Null.FromString,
        )
    self.SendNodeInfo = channel.unary_unary(
        '/project.SVM/SendNodeInfo',
        request_serializer=SVM__pb2.Node_Config.SerializeToString,
        response_deserializer=SVM__pb2.Null.FromString,
        )
    self.SendLearningInfo = channel.unary_unary(
        '/project.SVM/SendLearningInfo',
        request_serializer=SVM__pb2.Null.SerializeToString,
        response_deserializer=SVM__pb2.Null.FromString,
        )
    self.SendCompletionSignal = channel.unary_unary(
        '/project.SVM/SendCompletionSignal',
        request_serializer=SVM__pb2.Null.SerializeToString,
        response_deserializer=SVM__pb2.Null.FromString,
        )
    self.Start = channel.unary_unary(
        '/project.SVM/Start',
        request_serializer=SVM__pb2.Null.SerializeToString,
        response_deserializer=SVM__pb2.Null.FromString,
        )
    self.GetUpdate = channel.unary_unary(
        '/project.SVM/GetUpdate',
        request_serializer=SVM__pb2.Row.SerializeToString,
        response_deserializer=SVM__pb2.Row.FromString,
        )


class SVMServicer(object):
  """Interface exported by the server.

  """

  def GetWeights(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendNodeInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendLearningInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendCompletionSignal(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Start(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SVMServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetWeights': grpc.unary_unary_rpc_method_handler(
          servicer.GetWeights,
          request_deserializer=SVM__pb2.Row.FromString,
          response_serializer=SVM__pb2.Null.SerializeToString,
      ),
      'SendNodeInfo': grpc.unary_unary_rpc_method_handler(
          servicer.SendNodeInfo,
          request_deserializer=SVM__pb2.Node_Config.FromString,
          response_serializer=SVM__pb2.Null.SerializeToString,
      ),
      'SendLearningInfo': grpc.unary_unary_rpc_method_handler(
          servicer.SendLearningInfo,
          request_deserializer=SVM__pb2.Null.FromString,
          response_serializer=SVM__pb2.Null.SerializeToString,
      ),
      'SendCompletionSignal': grpc.unary_unary_rpc_method_handler(
          servicer.SendCompletionSignal,
          request_deserializer=SVM__pb2.Null.FromString,
          response_serializer=SVM__pb2.Null.SerializeToString,
      ),
      'Start': grpc.unary_unary_rpc_method_handler(
          servicer.Start,
          request_deserializer=SVM__pb2.Null.FromString,
          response_serializer=SVM__pb2.Null.SerializeToString,
      ),
      'GetUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.GetUpdate,
          request_deserializer=SVM__pb2.Row.FromString,
          response_serializer=SVM__pb2.Row.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'project.SVM', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
